baseURL = "https://svaus.github.io/"
title = "Go Code"

copyright = "© 2020."
draft = false
#publishDir = "docs"

# Pagination
paginate = 3
paginatePath = "page"

# Theme to use
theme = "material"

[params]
  author = "Sanket Verma"
  description = "example"
  github = "https://github.com/svaus"
  twitter = "example"
  misskey = "https://avatars2.githubusercontent.com/u/30944697?s=460&u=82446fbf268e19e122d90c5a3ea9e866911823eb&v=4"
  mastodon = "https://avatars2.githubusercontent.com/u/30944697?s=460&u=82446fbf268e19e122d90c5a3ea9e866911823eb&v=4"
  email = "sanket_verma@outlook.com"
  utterances = "example/svaus.github.io"
  avatar = "https://avatars2.githubusercontent.com/u/30944697?s=460&u=82446fbf268e19e122d90c5a3ea9e866911823eb&v=4"
  url = "https://svaus.github.io/"
  contributions = "post"